version: '3.8'
# replace 192.168.1.1 to real server ip
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-server
    ports:
      - "55008:2181"
    restart: always
    volumes:
      - /www/docker/kafka/zookeeper/data:/opt/zookeeper-3.4.13/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Asia/Shanghai"
    ulimits:
      nproc: 65535
      nofile:
        soft: 64000
        hard: 64000
    deploy:
      resources:
        limits:
          memory: 14G
          cpus: "8.00"
  kafka:
    image: wurstmeister/kafka:latest
    depends_on: [ zookeeper ]
    container_name: kafka-server
    restart: always
    ports:
      - "55009:9092"
      - "55010:9999"
    environment:
      HOSTNAME: 192.168.1.1
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.1:55009
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_JMX_PORT: 55010
      KAFKA_JMX_HOSTNAME: 192.168.1.1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      TZ: "Asia/Shanghai"
    volumes:
      - /www/docker/kafka/logs:/opt/kafka/logs
      - /www/docker/kafka/data:/kafka
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 14G
          cpus: "8.00"
  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    container_name: kafka-manager-server
    restart: always
    ports:
      - "55011:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      # APPLICATION_SECRET: superadmin
      KM_ARGS: -Djava.net.preferIPv4Stack=true
      TZ: "Asia/Shanghai"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 14G
          cpus: "8.00"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    container_name: kafka-ui-server
    depends_on:
      - kafka
    ports:
      # 映射到8090，因为8080一般还得挂其他的服务做测试
      - "55013:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-cluster-192.168.1.1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      # 配置 UI 使用用户名和密码连接 Kafka
      # KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      # KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      # KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="superadmin";'
      TZ: "Asia/Shanghai"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro